plugins:
  - 'jest'

extends:
  - 'eslint:recommended'
  - 'plugin:jest/recommended'

env:
  browser: true
  es6: true
  jest/globals: true

globals:
  chrome: true
  global: true

parserOptions:
  sourceType: module
  ecmaVersion: 8

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
